variable "aws_access_key" {
    default = "AKIA3DFA6QPFJW45WMXT"
}
variable "aws_secret_key" {
    default = "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"
}
variable "region" {
    default = "eu-west-3"
}

variable "aws_ami" {
    default = "ami-0f7cd40eac2214b37"
}

variable "talkdesk_keypair" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}
