variable "aws_access_key" {
    default = "youraccesskey"
}
variable "aws_secret_key" {
    default = "yoursecretkey"
}
variable "region" {
    default = "eu-central-1"
}


variable "talkdesk_keypair" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}
